spring:
   profiles: 
     active:
     - dev
---
server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-eureka-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间
      
eureka:
  instance: 
    hostname: eureka7001.com  #冒号后面必须有空格
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: eureka7001.com:7001/eureka/
      
---
server:
  port: 7001 #注册中心占用7001端口，冒号后面必须要有空格   
spring:
  profiles: test
  application: 
    name: microservicecloud-config-eureka-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间  
      
eureka:
  instance: 
    hostname: eureka7001.com  #冒号后面必须有空格
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: eureka7001.com:7001/eureka/     
      
      
      